# /etc/nginx/modsecurity.conf

SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecAuditEngine RelevantOnly
SecAuditLog /var/log/modsec_audit.log
SecAuditLogParts ABIJFHZ
SecDebugLog /var/log/modsec_debug.log
SecDebugLogLevel 3

# Include the OWASP CRS setup file
Include /etc/nginx/crs-setup.conf

# exceptions for www.uk-intech.de
SecRule REQUEST_URI "@beginsWith /plugins/system/jcemediabox/" \
    "id:1000002,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=920420"

# Include all the CRS rules
Include /etc/crs4/rules/*.conf
